/* parser generated by jison 0.4.4 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var prolog = (function(){
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"expressions":3,"program":4,"EOF":5,"clauselist":6,"query":7,"clause":8,"predicate":9,"PERIOD":10,"NECK":11,"predicatelist":12,"COMMA":13,"atom":14,"LEFTPAREN":15,"termlist":16,"RIGHTPAREN":17,"VARIABLE":18,"EQCMP":19,"string":20,"ASSIGN":21,"CUT":22,"term":23,"QUERYSYMBOL":24,"SMALLATOM":25,"STRING":26,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",10:"PERIOD",11:"NECK",13:"COMMA",15:"LEFTPAREN",17:"RIGHTPAREN",18:"VARIABLE",19:"EQCMP",21:"ASSIGN",22:"CUT",24:"QUERYSYMBOL",25:"SMALLATOM",26:"STRING"},
productions_: [0,[3,2],[4,1],[4,2],[4,1],[6,1],[6,2],[8,2],[8,4],[12,1],[12,3],[9,1],[9,4],[9,3],[9,3],[9,1],[16,1],[16,3],[23,1],[23,1],[7,3],[14,1],[14,1],[20,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1: 
          //typeof console !== 'undefined' ? console.log($$[$0-1]) : print($$[$0-1]);
          if(is_debug) {
            console.log("here 0");
          }
          return $$[$0-1]; 
        
break;
case 2:
          if(is_debug) {
            console.log("here 1");
          }
        
break;
case 3:
          if(is_debug) {
            console.log("here 1.1");
          }
        
break;
case 4:
          if(is_debug) {
            console.log("here 2");
          }
        
break;
case 5:
          if(is_debug) {
            console.log("here 3");
          }
        
break;
case 6:
          if(is_debug) {
            console.log("here 4");
          }
        
break;
case 7:
          if(is_debug) {
            console.log("here 5");
          }
        
break;
case 8:
         if(is_debug) {
           console.log("here 6 1: " + $$[$0-3]);
           console.log("_dbg rules.length: " + rules.length); 
         }
         if(rules.length > 0) {
	   header = rules.pop();
           if(is_debug) {
	     console.log("_dbg header rule name: " + header.name + " with arg: " + header.args[0]);
           }

           for(var i=0;i< header.args.length;i++) {
             if(is_debug) {
	       console.log("_dbg header rule name: " + header.name + " adding term: " + header.args[i]);
             }
             //header.args[i] = new Term(header.args[i]);
           }
	   while(rules.length > 0) {
	     var body_rule = rules.pop();
             if(is_debug) {
	       console.log("_dbg adding to header body rule name: " + body_rule.name);
               for(var i=0;i< body_rule.args.length;i++) {
	         console.log("  _dbg with arg: " + i + " "+ body_rule.args[i]);

               }
             }
             if(body_rule.name == 'write' && body_rule.args[0]) {
               if(is_debug) {
                 console.log("_dbg write body_rule.args[0]: " + body_rule.args[0]);
               }
               body_rule = new Rule('write(' + body_rule.args[0] + ')');
             }

             if(body_rule.name == 'i' && body_rule.args[0]) {
               if(is_debug) {
                 console.log("_dbg i body_rule.args[0]: " + body_rule.args[0].name);
               }
               body_rule = new Rule('i(' + body_rule.args[0].name + ')');
             }
             //iradiobtn(CPUCHOICE, {"Single":"single", "Dual":"dual"})
             if(body_rule.name == 'iradiobtn' && body_rule.args[0] && body_rule.args[1]) {
               if(is_debug) {
                 console.log("_dbg iradiobtn body_rule.args[0].name: " + body_rule.args[0].name + ' body_rule.args[1].name: ' + body_rule.args[1]);
               }
               body_rule = new Rule('iradiobtn(' + body_rule.args[0].name + ',' + body_rule.args[1] + ')');
               console.log("_dbg body_rule.name: " + body_rule.name);
             }


	     header.addRule(body_rule);
	   }
         }
         re.addRule(header);
        
break;
case 9:
         if(is_debug) {
           console.log("here 7 1: " + $$[$0]);
         }
         this.$=$$[$0];
        
break;
case 10:
         if(is_debug) {
           console.log("here 8");
         }
        
break;
case 11:
         if(is_debug) {
           console.log("here 9 1: " + $$[$0]);
         }
         this.$=$$[$0];
         var r = new Rule($$[$0]);
         rules.unshift(r);
        
break;
case 12:
         if(is_debug) {
           console.log("here 10");
           console.log("here 10 adding rule: " + $$[$0-3] + " with arg: " + args[0].name);
         }
         var r = new Rule($$[$0-3]);
         for(var i=0;i<args.length;i++) {
           r.addArg(args[i]); 
         }
         rules.unshift(r);
         args = [];
        
break;
case 13:
         this.$=$$[$0-2]+$$[$0-1]+$$[$0]
         var r = new Rule(this.$);
         rules.unshift(r);
         if(is_debug) {
           console.log("here 10.1: " + this.$);
         }

        
break;
case 14:
         this.$=$$[$0-2]+$$[$0-1]+$$[$0]
         var r = new Rule(this.$);
         rules.unshift(r);
         if(is_debug) {
           console.log("here 10.2: " + this.$);
         }

        
break;
case 15:
         this.$=$$[$0];
         var r = new Rule(this.$);
         rules.unshift(r);
         if(is_debug) {
           console.log("here 10.3: " + this.$);
         }

        
break;
case 16:
         if(is_debug) {
           console.log("here 11 1: " + $$[$0]);
         }
         this.$ = $$[$0]
        
break;
case 17:
         if(is_debug) {
           console.log("here 12");
         }
        
break;
case 18:
         if(is_debug) {
           console.log("here 14 1: " + $$[$0]);
         }
         this.$ = $$[$0];
         args.push($$[$0]);
        
break;
case 19:
         if(is_debug) {
           console.log("here 15 1: " + $$[$0]);
         }
         this.$ = $$[$0];
         var t_var = new Term(this.$);
         args.push(t_var);
        
break;
case 20:
         if(is_debug) {
           console.log("here 16 1: " + $$[$0-2]);
           console.log("here 16 2: " + $$[$0-1]);
         }
        
break;
case 21:
         if(is_debug) {
           console.log("here 18 1: " + $$[$0]);
         }
         this.$=$$[$0];
        
break;
case 22:
         if(is_debug) {
           console.log("here 19 1: " + $$[$0]);
         }
         this.$=$$[$0];
        
break;
case 23:
	this.$ = $$[$0].substring(1, $$[$0].length - 1);//js
	
break;
}
},
table: [{3:1,4:2,6:3,7:4,8:5,9:7,14:8,18:[1,9],20:12,22:[1,10],24:[1,6],25:[1,11],26:[1,13]},{1:[3]},{5:[1,14]},{5:[2,2],7:15,8:16,9:7,14:8,18:[1,9],20:12,22:[1,10],24:[1,6],25:[1,11],26:[1,13]},{5:[2,4]},{5:[2,5],18:[2,5],22:[2,5],24:[2,5],25:[2,5],26:[2,5]},{9:18,12:17,14:8,18:[1,9],20:12,22:[1,10],25:[1,11],26:[1,13]},{10:[1,19],11:[1,20]},{10:[2,11],11:[2,11],13:[2,11],15:[1,21]},{19:[1,22],21:[1,23]},{10:[2,15],11:[2,15],13:[2,15]},{10:[2,21],11:[2,21],13:[2,21],15:[2,21],17:[2,21]},{10:[2,22],11:[2,22],13:[2,22],15:[2,22],17:[2,22]},{10:[2,23],11:[2,23],13:[2,23],15:[2,23],17:[2,23]},{1:[2,1]},{5:[2,3]},{5:[2,6],18:[2,6],22:[2,6],24:[2,6],25:[2,6],26:[2,6]},{10:[1,24],13:[1,25]},{10:[2,9],13:[2,9]},{5:[2,7],18:[2,7],22:[2,7],24:[2,7],25:[2,7],26:[2,7]},{9:18,12:26,14:8,18:[1,9],20:12,22:[1,10],25:[1,11],26:[1,13]},{14:29,16:27,18:[1,30],20:12,23:28,25:[1,11],26:[1,13]},{20:31,26:[1,13]},{20:32,26:[1,13]},{5:[2,20]},{9:33,14:8,18:[1,9],20:12,22:[1,10],25:[1,11],26:[1,13]},{10:[1,34],13:[1,25]},{13:[1,36],17:[1,35]},{13:[2,16],17:[2,16]},{13:[2,18],17:[2,18]},{13:[2,19],17:[2,19]},{10:[2,13],11:[2,13],13:[2,13]},{10:[2,14],11:[2,14],13:[2,14]},{10:[2,10],13:[2,10]},{5:[2,8],18:[2,8],22:[2,8],24:[2,8],25:[2,8],26:[2,8]},{10:[2,12],11:[2,12],13:[2,12]},{14:29,18:[1,30],20:12,23:37,25:[1,11],26:[1,13]},{13:[2,17],17:[2,17]}],
defaultActions: {4:[2,4],14:[2,1],15:[2,3],24:[2,20]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    this.lexer.setInput(input);
    this.lexer.yy = this.yy;
    this.yy.lexer = this.lexer;
    this.yy.parser = this;
    if (typeof this.lexer.yylloc == 'undefined') {
        this.lexer.yylloc = {};
    }
    var yyloc = this.lexer.yylloc;
    lstack.push(yyloc);
    var ranges = this.lexer.options && this.lexer.options.ranges;
    if (typeof this.yy.parseError === 'function') {
        this.parseError = this.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    function lex() {
        var token;
        token = self.lexer.lex() || EOF;
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (this.lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + this.lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: this.lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: this.lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(this.lexer.yytext);
            lstack.push(this.lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = this.lexer.yyleng;
                yytext = this.lexer.yytext;
                yylineno = this.lexer.yylineno;
                yyloc = this.lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.call(yyval, yytext, yyleng, yylineno, this.yy, action[1], vstack, lstack);
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};


var rules = [];
var args = [];
var re = RuleEngine.getREInst();

/* generated by jison-lex 0.2.0 */
var lexer = (function(){
var lexer = {

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input) {
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len - 1);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            if (this.options.backtrack_lexer) {
                delete backup;
            }
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        if (this.options.backtrack_lexer) {
            delete backup;
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {

var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:return 26;
break;
case 2:return 26;
break;
case 3:return 'DIGIT';
break;
case 4:return 18;
break;
case 5:return 25;
break;
case 6:return 'LOWCASELETTER';
break;
case 7:return 'UPPERCASELETTER';
break;
case 8:return 19;
break;
case 9:return 21;
break;
case 10:return 13;
break;
case 11:return 10;
break;
case 12:return 11;
break;
case 13:return 22;
break;
case 14:return 24;
break;
case 15:return 15;
break;
case 16:return 17;
break;
case 17:return 5;
break;
case 18:return 'INVALID';
break;
}
},
rules: [/^(?:\s+)/,/^(?:"(\\["]|[^"])*")/,/^(?:'(\\[']|[^'])*')/,/^(?:[0-9])/,/^(?:[A-Z_]\w*)/,/^(?:[a-z_]\w*)/,/^(?:[a-z])/,/^(?:[A-Z])/,/^(?:==)/,/^(?:=)/,/^(?:,)/,/^(?:\.)/,/^(?::-)/,/^(?:!)/,/^(?:\?-)/,/^(?:\()/,/^(?:\))/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18],"inclusive":true}}
};
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


